baseURL = 'https://jhawk-cis.netlify.app/'
locale = 'en-us'
title = 'JHawk - CIS'
theme = 'beautifulhugo'

# hugo.toml

[pagination]
  pagerSize = 5

[Services]
  [Services.googleAnalytics]
    # id = "GTM-NNSFS9SD"

[Params]
  subtitle = "Anything worth doing is worth doing right"
  mainSections = ["post","posts"]
  logo = "/img/logo-JH-2026.png"
  favicon = "/img/logo-JH-2026.png"
  dateFormat = ":date_long"
  commit = false
  rss = false
  toc = false
  readingTime = false
  wordCount = false
  colorScheme = "light"
  socialShare = false
  showRelatedPosts = false
  hideAuthor = true
  disableFigureOverride = true
  headerImgStyle = "narrow"
  delayDisqus = true
  custom_css = "css/jhawk-custom.css"

[markup.goldmark.renderer] 
    unsafe = true

[[Params.bigimg]]
  src = "/img/wallpaper_code.png"
  desc = ""
  position = "center center"

[Params.author]
  email = "NeathawkJ@COD.edu"
  

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Codes"
    url = "page/code-examples/"
    weight = 3

[[menu.main]]
    name = "Games"
    url = "page/game-examples/"
    weight = 4

[[menu.main]]
    name = "Store"
    url = "/store"
    weight = 5

[[menu.main]]
    name = "COD Info"
    url = "page/cod/"
    weight = 6

[[menu.main]]
    name = "TCD Info"
    url = "page/tcd/"
    weight = 7
