[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.161.1"

[[redirects]]
  from = "/store*"
  to = "https://knighthawk0811-shop.fourthwall.com/"
  status = 301
  force = true